---
- hosts: yosemite
  user: devops

  vars_files:
    - vars/main.yml
    - vars/applications.yml

  roles:
    - homebrew
    - brew-cask
    - git-projects

  tasks:
    - name: Create Asgard Folder
      file: state=directory path=~/.asgard

    - name: Create Asgard Creditial Files
      copy: src=files/credentials dest=~/.asgard/credentials force=no

    - name: Create Boto File
      copy: src=files/boto dest=~/.boto force=no

    - name: Check if nginx conf needs update
      changed_when: False
      shell: cat /usr/local/etc/nginx/nginx.conf
      register: nginx_exists

    - name: Change file
      template: src=templates/nginx.j2 dest=/usr/local/etc/nginx/nginx.conf
      with_items: applications
      when: nginx_exists.stdout.find('www.deals') == -1

    - name: Move nginx redirects into place
      copy: src=files/nginx/redirects dest=/usr/local/etc/nginx/redirects.conf force=no

    - name: Create file if it isn't there
      file: state=touch path=/usr/local/etc/dnsmasq.conf

    - name: Check is DNSMasq needs to be create
      changed_when: False
      shell: cat /usr/local/etc/dnsmasq.conf
      register: dnsmasq_exists

    - name: Create DNSMasq file if needed
      copy: src=files/dnsmasq dest=/usr/local/etc/dnsmasq.conf
      when: dnsmasq_exists.stdout.find("/\.deals\/") == -1
