---
- hosts: localhost
  user: devops
  connection: local

  tasks:
    - name: Check if nginx conf needs update
      changed_when: False
      shell: cat ~/Desktop/testing.txt
      register: nginx_existest

    - name: Change file
      template: src=templates/test.j2 dest=~/Desktop/testing.txt
      with_items:
        - collection: [{total: www.deals }, {total: etproxy.deals }]
      when: nginx_existest.stdout.find('www.deals') == -1
