---
# tasks file for homebrew-cask-packages
- name: Homebrew Tap for Cask
  homebrew_tap: tap=caskroom/cask state=present

- name: Installing brew-cask
  homebrew: name=brew-cask state=latest

- name: Installing Mac Applications
  homebrew_cask: name={{ item }} state=installed
  with_items: homebrew_cask_packages_packages
